name: Scplugin
version: '1.0-SNAPSHOT'
main: monplugin.monplugin.Scplugin
api-version: '1.20'
commands:
  defi:
    description: ouvre le menu des defis
    usage: /defi
  biome:
    description: ouvre le menu des biomes
    usage: /biome
  test:
    description: frerot lit le nom
    usage: /test